name: Flutter CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Flutter Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'  # یا اپنا Flutter ورژن دیں

    - name: Show Flutter info
      run: flutter --version

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Run build_runner (if needed)
      run: flutter pub run build_runner build --delete-conflicting-outputs

  build:
    name: Flutter Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build IPA (iOS - optional)
      run: flutter build ipa --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 7

    - name: Upload iOS artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: flutter-ipa
        path: build/ios/ipa/*.ipa
        retention-days: 7
