name: Flutter App CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python-script:
    name: Run Quran Script
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Quran merge script
      run: python3 scripts/merge_quran.py

  flutter-test:
    name: Flutter Test
    runs-on: ubuntu-latest
    needs: python-script
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Analyze code
      run: flutter analyze

  flutter-build:
    name: Flutter Build
    runs-on: ubuntu-latest
    needs: flutter-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: alhaadi-app-apk
        path: build/app/output
