name: Flutter Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.10.0
        
      - name: Create Fresh Flutter Project
        run: |
          # مکمل نئی ڈائریکٹری بنائیں
          flutter create --org com.iqra --platforms android iqra_app
          cd iqra_app
          
          # Simple app بنائیں
          cat > lib/main.dart << 'EOF'
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Iqra Islamic Wisdom',
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Iqra Islamic Wisdom'),
        ),
        body: const Center(
          child: Text('Welcome to Iqra Islamic Wisdom v3.4'),
        ),
      ),
    );
  }
}
EOF
          
      - name: Build APK
        run: |
          cd iqra_app
          flutter clean
          flutter pub get
          flutter build apk --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: iqra-islamic-app
          path: iqra_app/build/app/outputs/flutter-apk/app-release.apk
