name: Build Flutter Web App

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'
        cache: true
        
    - name: Clean and Recreate Web Directory
      run: |
        echo "=== Cleaning existing files ==="
        rm -rf web
        rm -rf build
        
        echo "=== Creating proper web structure ==="
        flutter create --platforms web --project-name alhaadi_app .
        
        echo "=== Verifying web directory ==="
        ls -la web/
        
    - name: Install Dependencies
      run: flutter pub get
      
    - name: Build Web App
      run: flutter build web --release
      
    - name: Verify Final Build
      run: |
        echo "=== Final Build Contents ==="
        ls -la build/web/
        echo "=== Main Files Check ==="
        ls -la build/web/ | grep -E "(index.html|main.dart.js)"
        
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: flutter-web-app
        path: build/web/
        retention-days: 30
