name: Flutter Build and Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'
        cache: true
        
    - name: Setup Platforms Only (Without Overwriting)
      run: |
        # صرف platform ڈائریکٹریز بنائیں بغیر کوڈ overwrite کیے
        if [ ! -d "android" ]; then
          flutter create --platforms android .
        fi
        if [ ! -d "web" ]; then
          flutter create --platforms web .
        fi
        
    - name: Get Dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --release
      
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/
        retention-days: 7
