name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
      
    - name: Node.js Setup
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Dependencies Install
      run: npm ci
      
    - name: Build Application
      run: npm run build
      
    - name: Tests Run
      run: npm test
      
    - name: Build Artifacts Upload
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          dist/
          build/
          public/
        retention-days: 7
        compression-level: 9
        
    - name: Test Results Upload
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          coverage/
        retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
      
    - name: Build Artifacts Download
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: downloaded-artifacts/
        
    - name: Files List Show
      run: ls -la downloaded-artifacts/
      
    - name: Deploy to Server
      run: |
        echo "Deployment process here"
        # اپنی ڈپلائمنٹ کمانڈز یہاں شامل کریں
